server:
  servlet:
    context-path: /api/auth

spring:
  application:
    name: Auth
  datasource:
    url: jdbc:h2:file:./data/auth;NON_KEYWORDS=user
    username: sa
    password: password
    driverClassName: org.h2.Driver
    jpa:
      database-platform: org.hibernate.dialect.H2Dialect
  jpa:
    hibernate:
      generate-ddl: true
      ddl-auto: update
  jwt:
    shared-key: 5vETpkOhKFK2X3uxcOTzpugaN2CpLQlj

springdoc:
  swagger-ui:
    path: "/swagger-ui.html"